branch-defaults:
  default:
    environment: hw-eb-test-2-dev
    group_suffix: null
global:
  application_name: hw-eb-test-2
  branch: null
  default_ec2_keyname: Coderp Virginia
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: CODERP-EB
  repository: null
  sc: null
  workspace_type: Application
